gpus: "0"  # 使用GPU 0和1
model: tcn
# task: count
task: vadosd
feats:
  type: mfcc_kaldi # filterbanks actually if num ceps == num mels
  hop_size: 0.01
  n_feats: 80
  inject_noise: false
log_dir: exp/tcn
mels:
  n_mels: 40
  n_fft: 400
  win_length: 400
  hop_length: 160
mfcc:
  sample_rate: 16000
  n_mfcc: 40
  log_mels: true
mfcc_kaldi:
  use_energy: false
  sample_frequency: 16000
  num_mel_bins: 80
  num_ceps: 80
  low_freq: 40
  high_freq: -400
  dither: 0.0
fbank_kaldi:
  use_energy: false
  sample_frequency: 16000
  num_mel_bins: 80
  low_freq: 80
  high_freq: -400
  dither: 0.00000001
spectrogram_kaldi:
  sample_frequency: 16000
  dither: 0.0
labels:
  merge_vad: 0.0
  merge_ph: 0.0
  collar_ph: 0.00
data:
  n_classes: 3
  segment: 300
  fs: 16000
  custom_json_folder:
  chime6_root: /mnt/sdb2/lsj/datasets/AMI/media/sam/bx500/amicorpus/audio/
  # label_test: /datasets/AMI/media/sam/bx500/amicorpus/fa_labels/dev/ 
  label_test: /mnt/sdb2/lsj/datasets/AMI/media/sam/bx500/amicorpus/fa_labels/eval/ 
opt:
  learning_rate: 0.001  
  # lr: 0.00015
  weight_decay: !!float 1e-5
training:
  batch_size: 1
  num_workers: 8
  n_epochs: 20
  gradient_clip: 5
  accumulate_batches: 1
augmentation:
  # probs: None
  probs: [0.3, 0.7]
  abs_stats: [-16.7, 7]
  rel_stats: [2.78, 4]

